import { BookOpen, BookText, Brain, Briefcase, Baby, Globe } from "lucide-react"
// Mock Categories
export const mockCategories = [
  {
    id: 1,
    name: "Văn học",
    icon: <BookOpen size={32} />,
    bookCount: 1250,
    description: "Sách văn học Việt Nam và thế giới",
  },
  {
    id: 2,
    name: "Kinh tế",
    icon: <Briefcase size={32} />,
    bookCount: 850,
    description: "Sách về kinh tế, kinh doanh, tài chính",
  },
  {
    id: 3,
    name: "Kỹ năng sống",
    icon: <Brain size={32} />,
    bookCount: 620,
    description: "Sách về phát triển bản thân và kỹ năng sống",
  },
  {
    id: 4,
    name: "Sách thiếu nhi",
    icon: <Baby size={32} />,
    bookCount: 780,
    description: "Sách dành cho trẻ em và thiếu niên",
  },
  {
    id: 5,
    name: "Sách ngoại ngữ",
    icon: <Globe size={32} />,
    bookCount: 450,
    description: "Sách học ngoại ngữ và sách bằng tiếng nước ngoài",
  },
  {
    id: 6,
    name: "Giáo khoa - Tham khảo",
    icon: <BookText size={32} />,
    bookCount: 920,
    description: "Sách giáo khoa và tài liệu tham khảo",
  },
]

// Mock Books
export const mockBooks = [
  {
    id: 1,
    title: "Nhà Giả Kim",
    author: "Paulo Coelho",
    category_id: 1,
    publisher: "NXB Hội Nhà Văn",
    publish_year: 2020,
    pages: 228,
    language: "Tiếng Việt",
    rental_price: 25000,
    deposit_price: 150000,
    available_quantity: 15,
    description:
      "Nhà giả kim là cuốn sách được xuất bản lần đầu ở Brasil năm 1988, và trở thành một trong những cuốn sách bán chạy nhất mọi thời đại. Tác phẩm kể về Santiago, một cậu bé chăn cừu người Tây Ban Nha, đã thực hiện một cuộc hành trình đến Kim tự tháp Ai Cập sau khi có một giấc mơ lặp đi lặp lại về việc tìm thấy kho báu ở đó.",
    cover_image: "/Book.jpg",
  },
  {
    id: 2,
    title: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    category_id: 3,
    publisher: "NXB Tổng hợp TP.HCM",
    publish_year: 2019,
    pages: 320,
    language: "Tiếng Việt",
    rental_price: 30000,
    deposit_price: 180000,
    available_quantity: 10,
    description:
      "Đắc Nhân Tâm là một trong những cuốn sách nổi tiếng nhất về phát triển bản thân. Cuốn sách cung cấp những lời khuyên về cách thức cư xử, ứng xử và giao tiếp với mọi người để đạt được thành công trong cuộc sống.",
    cover_image: "https://salt.tikicdn.com/cache/w1200/ts/product/df/7d/da/d340edda2b0eacb7ddc47537cddb5e08.jpg",
  },
  {
    id: 3,
    title: "Tôi Tài Giỏi, Bạn Cũng Thế",
    author: "Adam Khoo",
    category_id: 3,
    publisher: "NXB Phụ Nữ",
    publish_year: 2018,
    pages: 285,
    language: "Tiếng Việt",
    rental_price: 28000,
    deposit_price: 160000,
    available_quantity: 8,
    description:
      "Tôi Tài Giỏi, Bạn Cũng Thế là cuốn sách bán chạy nhất của Adam Khoo, một doanh nhân thành đạt người Singapore. Cuốn sách chia sẻ những phương pháp học tập hiệu quả giúp bạn phát huy tối đa tiềm năng của bản thân.",
    cover_image: "/Book.jpg",
  },
  {
    id: 4,
    title: "Sapiens: Lược Sử Loài Người",
    author: "Yuval Noah Harari",
    category_id: 1,
    publisher: "NXB Thế Giới",
    publish_year: 2019,
    pages: 560,
    language: "Tiếng Việt",
    rental_price: 35000,
    deposit_price: 200000,
    available_quantity: 5,
    description:
      "Sapiens là một cuốn sách về lịch sử loài người từ thời kỳ đồ đá cũ đến thế kỷ 21. Tác giả Yuval Noah Harari đã mô tả sự phát triển của loài người qua bốn cuộc cách mạng lớn: nhận thức, nông nghiệp, thống nhất và khoa học.",
    cover_image: "/Book.jpg",
  },
  {
    id: 5,
    title: "Người Giàu Có Nhất Thành Babylon",
    author: "George S. Clason",
    category_id: 2,
    publisher: "NXB Lao Động",
    publish_year: 2020,
    pages: 208,
    language: "Tiếng Việt",
    rental_price: 25000,
    deposit_price: 150000,
    available_quantity: 12,
    description:
      "Người Giàu Có Nhất Thành Babylon là một cuốn sách kinh điển về tài chính cá nhân. Thông qua những câu chuyện từ thành Babylon cổ đại, cuốn sách đưa ra những bài học quý giá về cách làm giàu và quản lý tài chính.",
    cover_image: "/Book.jpg",
  },
  {
    id: 6,
    title: "Dám Nghĩ Lớn",
    author: "David J. Schwartz",
    category_id: 3,
    publisher: "NXB Lao Động - Xã Hội",
    publish_year: 2017,
    pages: 320,
    language: "Tiếng Việt",
    rental_price: 28000,
    deposit_price: 160000,
    available_quantity: 7,
    description:
      "Dám Nghĩ Lớn là cuốn sách kinh điển về phát triển bản thân. Tác giả David J. Schwartz đưa ra những phương pháp thực tế giúp bạn phát triển tư duy tích cực và đạt được thành công trong cuộc sống.",
    cover_image: "/Book.jpg",
  },
  {
    id: 7,
    title: "Bí Mật Của May Mắn",
    author: "Rhonda Byrne",
    category_id: 3,
    publisher: "NXB Lao Động",
    publish_year: 2018,
    pages: 198,
    language: "Tiếng Việt",
    rental_price: 26000,
    deposit_price: 150000,
    available_quantity: 9,
    description:
      "Bí Mật Của May Mắn là cuốn sách nổi tiếng về luật hấp dẫn. Cuốn sách giải thích cách thức vũ trụ hoạt động và làm thế nào để bạn có thể sử dụng luật hấp dẫn để đạt được những điều mình mong muốn.",
    cover_image: "/Book.jpg",
  },
  {
    id: 8,
    title: "Hành Trình Về Phương Đông",
    author: "Baird T. Spalding",
    category_id: 1,
    publisher: "NXB Hồng Đức",
    publish_year: 2019,
    pages: 256,
    language: "Tiếng Việt",
    rental_price: 27000,
    deposit_price: 160000,
    available_quantity: 6,
    description:
      "Hành Trình Về Phương Đông là câu chuyện về chuyến đi của một đoàn khoa học gồm các giáo sư đại học Hoa Kỳ đến Ấn Độ và Tây Tạng để tìm hiểu về những hiện tượng kỳ bí và triết lý phương Đông.",
    cover_image: "/Book.jpg",
  },
  {
    id: 9,
    title: "Đời Ngắn Đừng Ngủ Dài",
    author: "Robin Sharma",
    category_id: 3,
    publisher: "NXB Trẻ",
    publish_year: 2018,
    pages: 228,
    language: "Tiếng Việt",
    rental_price: 25000,
    deposit_price: 150000,
    available_quantity: 10,
    description:
      "Đời Ngắn Đừng Ngủ Dài là cuốn sách truyền cảm hứng của Robin Sharma. Cuốn sách đưa ra 101 bài học giúp bạn sống một cuộc đời đáng sống và đạt được thành công trong công việc và cuộc sống.",
    cover_image: "/Book.jpg",
  },
  {
    id: 10,
    title: "Cà Phê Cùng Tony",
    author: "Tony Buổi Sáng",
    category_id: 3,
    publisher: "NXB Trẻ",
    publish_year: 2017,
    pages: 268,
    language: "Tiếng Việt",
    rental_price: 26000,
    deposit_price: 150000,
    available_quantity: 8,
    description:
      "Cà Phê Cùng Tony là tập hợp những bài viết của tác giả Tony Buổi Sáng về nhiều chủ đề khác nhau trong cuộc sống. Cuốn sách mang đến những góc nhìn mới mẻ và thú vị về cuộc sống, công việc và các mối quan hệ.",
    cover_image: "/Book.jpg",
  },
  {
    id: 11,
    title: "Tư Duy Phản Biện",
    author: "Richard Paul",
    category_id: 3,
    publisher: "NXB Lao Động",
    publish_year: 2020,
    pages: 240,
    language: "Tiếng Việt",
    rental_price: 28000,
    deposit_price: 160000,
    available_quantity: 7,
    description:
      "Tư Duy Phản Biện là cuốn sách giúp bạn phát triển kỹ năng tư duy phản biện - một kỹ năng quan trọng trong thời đại thông tin hiện nay. Cuốn sách cung cấp các công cụ và phương pháp để phân tích, đánh giá và đưa ra quyết định một cách hợp lý.",
    cover_image: "/Book.jpg",
  },
  {
    id: 12,
    title: "Khéo Ăn Nói Sẽ Có Được Thiên Hạ",
    author: "Trác Nhã",
    category_id: 3,
    publisher: "NXB Văn Học",
    publish_year: 2018,
    pages: 320,
    language: "Tiếng Việt",
    rental_price: 27000,
    deposit_price: 160000,
    available_quantity: 9,
    description:
      "Khéo Ăn Nói Sẽ Có Được Thiên Hạ là cuốn sách về nghệ thuật giao tiếp. Cuốn sách cung cấp những kỹ năng và phương pháp giúp bạn giao tiếp hiệu quả trong các tình huống khác nhau của cuộc sống.",
    cover_image: "/Book.jpg",
  },
  {
    id: 13,
    title: "Đừng Bao Giờ Đi Ăn Một Mình",
    author: "Keith Ferrazzi",
    category_id: 2,
    publisher: "NXB Lao Động",
    publish_year: 2019,
    pages: 312,
    language: "Tiếng Việt",
    rental_price: 29000,
    deposit_price: 170000,
    available_quantity: 6,
    description:
      "Đừng Bao Giờ Đi Ăn Một Mình là cuốn sách về nghệ thuật xây dựng mối quan hệ trong kinh doanh. Tác giả Keith Ferrazzi chia sẻ những bí quyết để xây dựng mạng lưới quan hệ rộng lớn và bền vững.",
    cover_image: "/Book.jpg",
  },
  {
    id: 14,
    title: "Điểm Đến Của Cuộc Đời",
    author: "Nguyên Phong",
    category_id: 1,
    publisher: "NXB Hồng Đức",
    publish_year: 2018,
    pages: 280,
    language: "Tiếng Việt",
    rental_price: 26000,
    deposit_price: 150000,
    available_quantity: 8,
    description:
      "Điểm Đến Của Cuộc Đời là cuốn sách về hành trình tìm kiếm ý nghĩa cuộc sống. Cuốn sách kể về hành trình của một người đàn ông trẻ đi tìm câu trả lời cho những câu hỏi lớn về cuộc sống và vũ trụ.",
    cover_image: "/Book.jpg",
  },
  {
    id: 15,
    title: "Bí Mật Tư Duy Triệu Phú",
    author: "T. Harv Eker",
    category_id: 2,
    publisher: "NXB Lao Động",
    publish_year: 2019,
    pages: 240,
    language: "Tiếng Việt",
    rental_price: 28000,
    deposit_price: 160000,
    available_quantity: 7,
    description:
      "Bí Mật Tư Duy Triệu Phú là cuốn sách về tư duy làm giàu. Tác giả T. Harv Eker chỉ ra những khác biệt trong tư duy giữa người giàu và người nghèo, từ đó giúp bạn phát triển tư duy của người giàu.",
    cover_image: "/Book.jpg",
  },
  {
    id: 16,
    title: "Dạy Con Làm Giàu",
    author: "Robert Kiyosaki",
    category_id: 2,
    publisher: "NXB Trẻ",
    publish_year: 2020,
    pages: 320,
    language: "Tiếng Việt",
    rental_price: 30000,
    deposit_price: 180000,
    available_quantity: 5,
    description:
      "Dạy Con Làm Giàu là cuốn sách kinh điển về tài chính cá nhân. Tác giả Robert Kiyosaki chia sẻ những bài học về tài chính mà ông học được từ 'người cha giàu' và 'người cha nghèo', giúp bạn hiểu rõ hơn về cách quản lý tiền bạc và đầu tư.",
    cover_image: "/Book.jpg",
  },
]

// Mock Authors
export const mockAuthors = [
  {
    id: 1,
    name: "Paulo Coelho",
    country: "Brazil",
    bio: "Paulo Coelho là một nhà văn người Brazil nổi tiếng với cuốn tiểu thuyết Nhà Giả Kim.",
  },
  {
    id: 2,
    name: "Dale Carnegie",
    country: "Mỹ",
    bio: "Dale Carnegie là một nhà văn và nhà thuyết trình người Mỹ, nổi tiếng với cuốn sách Đắc Nhân Tâm.",
  },
  {
    id: 3,
    name: "Adam Khoo",
    country: "Singapore",
    bio: "Adam Khoo là một doanh nhân, nhà đầu tư và tác giả người Singapore.",
  },
  {
    id: 4,
    name: "Yuval Noah Harari",
    country: "Israel",
    bio: "Yuval Noah Harari là một nhà sử học và giáo sư tại Đại học Hebrew ở Jerusalem.",
  },
  {
    id: 5,
    name: "George S. Clason",
    country: "Mỹ",
    bio: "George Samuel Clason là một nhà văn người Mỹ, nổi tiếng với cuốn sách Người Giàu Có Nhất Thành Babylon.",
  },
  {
    id: 6,
    name: "Robin Sharma",
    country: "Canada",
    bio: "Robin Sharma là một nhà văn người Canada gốc Ấn Độ, nổi tiếng với cuốn sách Nhà Lãnh Đạo Không Chức Danh.",
  },
  {
    id: 7,
    name: "Robert Kiyosaki",
    country: "Mỹ",
    bio: "Robert Kiyosaki là một doanh nhân, nhà đầu tư và tác giả người Mỹ, nổi tiếng với cuốn sách Dạy Con Làm Giàu.",
  },
  {
    id: 8,
    name: "Tony Buổi Sáng",
    country: "Việt Nam",
    bio: "Tony Buổi Sáng là bút danh của một tác giả người Việt Nam, nổi tiếng với cuốn sách Cà Phê Cùng Tony.",
  },
  {
    id: 9,
    name: "Nguyên Phong",
    country: "Việt Nam",
    bio: "Nguyên Phong là bút danh của một tác giả người Việt Nam, nổi tiếng với nhiều cuốn sách về tâm linh và phát triển bản thân.",
  },
  {
    id: 10,
    name: "T. Harv Eker",
    country: "Mỹ",
    bio: "T. Harv Eker là một doanh nhân, nhà đầu tư và tác giả người Mỹ, nổi tiếng với cuốn sách Bí Mật Tư Duy Triệu Phú.",
  },
]

// Mock User
export const mockUser = {
  id: 1,
  email: "user@example.com",
  full_name: "Nguyễn Văn A",
  phone: "0123456789",
  gender: "Male",
  age: 30,
  role_id: 2, // Regular user role
  addresses: [
    {
      id: 1,
      street: "123 Đường Lê Lợi",
      ward: "Phường Bến Nghé",
      district: "Quận 1",
      city: "TP.HCM",
      province: "Hồ Chí Minh",
      is_default: true,
    },
    {
      id: 2,
      street: "456 Đường Nguyễn Huệ",
      ward: "Phường Bến Nghé",
      district: "Quận 1",
      city: "TP.HCM",
      province: "Hồ Chí Minh",
      is_default: false,
    },
  ],
}

// Mock Orders
export const mockOrders = [
  {
    id: 100001,
    user_id: 1,
    rental_date: "2023-06-15T10:30:00",
    due_date: "2023-06-29T10:30:00",
    return_date: "2023-06-28T14:45:00",
    status: "Returned", // Active, Returned, Overdue, Cancelled
    payment_status: "Paid", // Paid, Pending
    payment_method: "Cash", // Cash, BankTransfer, EWallet
    delivery_method: "Pickup", // Pickup, Delivery
    total_rental_price: 80000,
    total_deposit: 460000,
    shipping_fee: 0,
    late_fee: 0,
    notes: "Tôi sẽ đến lấy sách vào buổi chiều.",
    items: [
      {
        id: 1,
        book_id: 1,
        book_title: "Nhà Giả Kim",
        quantity: 1,
        rental_price: 25000,
        deposit_price: 150000,
        status: "Returned",
      },
      {
        id: 2,
        book_id: 5,
        book_title: "Người Giàu Có Nhất Thành Babylon",
        quantity: 1,
        rental_price: 25000,
        deposit_price: 150000,
        status: "Returned",
      },
      {
        id: 3,
        book_id: 9,
        book_title: "Đời Ngắn Đừng Ngủ Dài",
        quantity: 1,
        rental_price: 30000,
        deposit_price: 160000,
        status: "Returned",
      },
    ],
  },
  {
    id: 100002,
    user_id: 1,
    rental_date: "2023-07-10T09:15:00",
    due_date: "2023-07-24T09:15:00",
    return_date: null,
    status: "Active",
    payment_status: "Paid",
    payment_method: "BankTransfer",
    delivery_method: "Delivery",
    total_rental_price: 86000,
    total_deposit: 490000,
    shipping_fee: 30000,
    late_fee: 0,
    notes: "",
    items: [
      {
        id: 4,
        book_id: 2,
        book_title: "Đắc Nhân Tâm",
        quantity: 1,
        rental_price: 30000,
        deposit_price: 180000,
        status: "Active",
      },
      {
        id: 5,
        book_id: 7,
        book_title: "Bí Mật Của May Mắn",
        quantity: 1,
        rental_price: 26000,
        deposit_price: 150000,
        status: "Active",
      },
      {
        id: 6,
        book_id: 12,
        book_title: "Khéo Ăn Nói Sẽ Có Được Thiên Hạ",
        quantity: 1,
        rental_price: 30000,
        deposit_price: 160000,
        status: "Active",
      },
    ],
  },
  {
    id: 100003,
    user_id: 1,
    rental_date: "2023-05-20T14:00:00",
    due_date: "2023-06-03T14:00:00",
    return_date: "2023-06-05T11:30:00",
    status: "Returned",
    payment_status: "Paid",
    payment_method: "EWallet",
    delivery_method: "Pickup",
    total_rental_price: 55000,
    total_deposit: 310000,
    shipping_fee: 0,
    late_fee: 10000,
    notes: "",
    items: [
      {
        id: 7,
        book_id: 3,
        book_title: "Tôi Tài Giỏi, Bạn Cũng Thế",
        quantity: 1,
        rental_price: 28000,
        deposit_price: 160000,
        status: "Returned",
      },
      {
        id: 8,
        book_id: 10,
        book_title: "Cà Phê Cùng Tony",
        quantity: 1,
        rental_price: 27000,
        deposit_price: 150000,
        status: "Returned",
      },
    ],
  },
  {
    id: 100004,
    user_id: 1,
    rental_date: "2023-08-05T16:45:00",
    due_date: "2023-08-19T16:45:00",
    return_date: null,
    status: "Cancelled",
    payment_status: "Refunded",
    payment_method: "Cash",
    delivery_method: "Delivery",
    total_rental_price: 65000,
    total_deposit: 350000,
    shipping_fee: 30000,
    late_fee: 0,
    notes: "Hủy đơn hàng do không thể nhận sách vào thời gian này.",
    items: [
      {
        id: 9,
        book_id: 4,
        book_title: "Sapiens: Lược Sử Loài Người",
        quantity: 1,
        rental_price: 35000,
        deposit_price: 200000,
        status: "Cancelled",
      },
      {
        id: 10,
        book_id: 14,
        book_title: "Điểm Đến Của Cuộc Đời",
        quantity: 1,
        rental_price: 30000,
        deposit_price: 150000,
        status: "Cancelled",
      },
    ],
  },
]
